kind: Service
apiVersion: v1
metadata:
  labels:
    app: xpctl-server
  name: xpctl-server
spec:
  selector:
    app: xpctl-server
  ports:
    - port: 5310
      targetPort: 5310
  type: NodePort
status:
  loadBalancer: {}
